import os
import re
from pathlib import Path

# --- CONFIGURATION ---
# Update this path to your local project directory
BASE_DIR = Path(r"C:\Users\elisa\OneDrive\Documents\texas-special-ed-site\es-districts")

# The long list you provided
DISTRICT_LIST_RAW = """
HOUSTON ISDDALLAS ISDCYPRESS-FAIRBANKS ISDNORTHSIDE ISDKATY ISDFORT BEND ISDCONROE ISDAUSTIN ISDFORT WORTH ISDFRISCO ISDNORTH EAST ISDALDINE ISDARLINGTON ISDKLEIN ISDGARLAND ISDHUMBLE ISDEL PASO ISDLEWISVILLE ISDROUND ROCK ISDLAMAR CISDSOCORRO ISDPLANO ISDPASADENA ISDSAN ANTONIO ISDKILLEEN ISDLEANDER ISDUNITED ISDCLEAR CREEK ISDALIEF ISDMESQUITE ISDRICHARDSON ISDBROWNSVILLE ISDMANSFIELD ISDYSLETA ISDECTOR COUNTY ISDSPRING ISDEDINBURG CISDDENTON ISDCORPUS CHRISTI ISDSPRING BRANCH ISDNORTHWEST ISDKELLER ISDPROSPER ISDIRVING ISDALVIN ISDCOMAL ISDMIDLAND ISDPHARR-SAN JUAN-ALAMO ISDAMARILLO ISDGRAND PRAIRIE ISDPFLUGERVILLE ISDWYLIE ISDHALLSVILLE ISDHAYS CISDCARROLLTON-FARMERS BRANCH ISDLUBBOCK ISDGOOSE CREEK CISDEAGLE MT-SAGINAW ISDJUDSON ISDMCKINNEY ISDHURST-EULESS-BEDFORD ISDLA JOYA ISDTOMBALL ISDBIRDVILLE ISDPEARLAND ISDGALENA PARK ISDALLEN ISDMCALLEN ISDNEW CANEY ISDROCKWALL ISDLAREDO ISDTYLER ISDFORNEY ISDCROWLEY ISDHARLINGEN CISDBEAUMONT ISDBRYAN ISDWESLACO ISDSCHERTZ-CIBOLO-U CITY ISDMAGNOLIA ISDSOUTHWEST ISDABILENE ISDCOLLEGE STATION ISDGEORGETOWN ISDEAGLE PASS ISDBELTON ISDGRAPEVINE-COLLEYVILLE ISDFORT STOCKTON ISDWACO ISDBASTROP ISDCOPPELL ISDSAN ANGELO ISDDONNA ISDMISSION CISDVICTORIA ISDBURLESON ISDWICHITA FALLS ISDDICKINSON ISDCLEVELAND ISDROSCOE COLLEGIATE ISDDEER PARK ISDFRENSHIP ISDDEL VALLE ISDCANYON ISDDUNCANVILLE ISDEAST CENTRAL ISDMIDLOTHIAN ISDWAXAHACHIE ISDBRAZOSPORT ISDBOERNE ISDLAKE TRAVIS ISDHUNTSVILLE ISDSHELDON ISDHARLANDALE ISDHUTTO ISDLOS FRESNOS CISDCLINT ISDROYSE CITY ISDMANOR ISDPRINCETON ISDWALLER ISDNEW BRAUNFELS ISDMONTGOMERY ISDSHARYLAND ISDLIBERTY HILL ISDSAN FELIPE-DEL RIO CISDMEDINA VALLEY ISDCHANNELVIEW ISDWILLIS ISDSAN BENITO CISDMIDWAY ISDTEMPLE ISDRIO GRANDE CITY GRULLA ISDDRIPPING SPRINGS ISDALEDO ISDEDGEWOOD ISDSAN MARCOS CISDLONGVIEW ISDCARROLL ISDPORT ARTHUR ISDLITTLE ELM ISDLUBBOCK-COOPER ISDWEATHERFORD ISDGRANBURY ISDBARBERS HILL ISDSHERMAN ISDCOPPERAS COVE ISDMELISSA ISDTEXAS CITY ISDEANES ISDAZLE ISDSEGUIN ISDTEXARKANA ISDANGLETON ISDLA PORTE ISDHIGHLAND PARK ISDCROSBY ISDSOUTH SAN ANTONIO ISDCRANDALL ISDCLEBURNE ISDLUFKIN ISDWHITE SETTLEMENT ISDLANCASTER ISDLOCKHART ISDRED OAK ISDENNIS ISDCEDAR HILL ISDFRIENDSWOOD ISDARGYLE ISDANNA ISDJOSHUA ISDROMA ISDCORSICANA ISDGALVESTON ISDELGIN ISDNACOGDOCHES ISDCANUTILLO ISDSOUTHSIDE ISDSPLENDORA ISDDAYTON ISDFLOUR BLUFF ISDDESOTO ISDPORT NECHES-GROVES ISDCELINA ISDNEDERLAND ISDCOMMUNITY ISDGREENVILLE ISDMOUNT PLEASANT ISDGREGORY-PORTLAND ISDEVERMAN ISDDENISON ISDTERRELL ISDBRENHAM ISDALAMO HEIGHTS ISDJACKSONVILLE ISDMARSHALL ISDWHITEHOUSE ISDSOUTH TEXAS ISDLINDALE ISDKERRVILLE ISDAUBREY ISDPINE TREE ISDDUMAS ISDKAUFMAN ISDSANTA FE ISDALICE ISDSOMERSET ISDVALLEY VIEW ISDSULPHUR SPRINGS ISDANDREWS ISDSPRINGTOWN ISDVIDOR ISDJARRELL ISDLUMBERTON ISDEDCOUCH-ELSA ISDPLAINVIEW ISDFLORESVILLE ISDUVALDE CISDLIVINGSTON ISDMARBLE FALLS ISDMERCEDES ISDHEREFORD ISDMABANK ISDLOVEJOY ISDCASTLEBERRY ISDPARIS ISDALVARADO ISDDECATUR ISDCHAPEL HILL ISDCALALLEN ISDLAKE DALLAS ISDNEEDVILLE ISDHUFFMAN ISDLAMPASAS ISDSTEPHENVILLE ISDTULOSO-MIDWAY ISDLA VERNIA ISDKILGORE ISD CALHOUN COUNTY ISD BAY CITY ISD PLEASANTON ISD BROWNWOOD ISD BIG SPRING ISD GREENWOOD ISD LITTLE CYPRESS-MAURICEVILLE CISD MINERAL WELLS ISD ZAPATA COUNTY ISD EL CAMPO ISD LAKE WORTH ISD HENDERSON ISD BURNET CISD GODLEY ISD BRIDGE CITY ISD PAMPA ISD NAVASOTA ISD GAINESVILLE ISD SEALY ISD SEMINOLE ISD CADDO MILLS ISD BEEVILLE ISD BURKBURNETT ISD FERRIS ISD PALESTINE ISD GILMER ISD CHINA SPRING ISD QUINLAN ISD TAYLOR ISD PECOS-BARSTOW-TOYAH ISD LA VEGA ISD SANGER ISD FREDERICKSBURG ISD COLUMBIA-BRAZORIA ISD ATHENS ISD BULLARD ISD HUDSON ISD HIDALGO ISD ROCKPORT-FULTON ISD HARDIN-JEFFERSON ISD SAN ELIZARIO ISD KENNEDALE ISD ROYAL ISD WILLS POINT ISD NAVARRO ISD GATESVILLE ISD LA FERIA ISD CARTHAGE ISD VAN ALSTYNE ISD WEST ORANGE-COVE CISD SILSBEE ISD LEVELLAND ISD GONZALES ISD KRUM ISD KINGSVILLE ISD WIMBERLEY ISD BROWNSBORO ISD LIBERTY ISD ROBSTOWN ISD FARMERSVILLE ISD NORTH LAMAR ISD ROBINSON ISD
"""

def get_slug(name):
    """Converts 'AUSTIN ISD' to 'austin-isd'."""
    return name.strip().lower().replace(" ", "-").replace("/", "-")

def parse_districts(raw_text):
    """
    Parses the raw text list. 
    Matches patterns ending in ISD or CISD even if they are mashed together.
    """
    pattern = r".+? [CI]?SD"
    matches = re.findall(pattern, raw_text)
    return [m.strip() for m in matches]

def main():
    districts = parse_districts(DISTRICT_LIST_RAW)
    
    if not BASE_DIR.exists():
        print(f"Error: Directory {BASE_DIR} does not exist.")
        return

    missing_folders = []
    missing_indices = []
    found_count = 0

    print(f"Auditing {len(districts)} districts in {BASE_DIR}...\n")

    for district_name in districts:
        slug = get_slug(district_name)
        folder_path = BASE_DIR / slug
        index_path = folder_path / "index.html"

        if not folder_path.exists():
            # Try checking if folder exists with original name case
            folder_path_alt = BASE_DIR / district_name
            if folder_path_alt.exists():
                folder_path = folder_path_alt
                index_path = folder_path / "index.html"
            else:
                missing_folders.append(district_name)
                continue

        if not index_path.exists():
            missing_indices.append(f"{district_name} ({slug})")
        else:
            found_count += 1

    # --- REPORTING ---
    print(f"✅ Audit Complete. Found {found_count} valid index files.")
    
    if missing_folders:
        print(f"\n📁 MISSING FOLDERS ({len(missing_folders)}):")
        for folder in missing_folders:
            print(f"  - {folder}")
            
    if missing_indices:
        print(f"\n📄 MISSING index.html FILES ({len(missing_indices)}):")
        for item in missing_indices:
            print(f"  - {item}")

    if not missing_folders and not missing_indices:
        print("\n✨ Awesome! No missing folders or index files found.")

if __name__ == "__main__":
    main()